name: test build process

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    matrix: 
      include: 
        - toolset: clang
            cxxstd: "14,17"
            os: ubuntu-20.04
        - toolset: gcc-10
            cxxstd: "14,17"
            os: ubuntu-20.04
            install: g++-10
        - toolset: clang
            cxxstd: "14,17"
            os: macos-11

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Prepare llvm build directory name
        id: llvm-build-dir
        run: |
          echo "commit=$(git submodule status llvm | awk '{print $1;}')" >> $GITHUB_OUTPUT
      - name: Cache llvm build directory
        uses: actions/cache@v3
        with:
          path: llvm
          key: build-${{ steps.llvm-build-dir.outputs.commit }}
      - name: Test build
        run: bash ./tests/Actions/TestBuild.sh  llvm/build-${{ steps.llvm-build-dir.outputs.commit }}
