name: test build process

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

# ToDo : Cache llvm build to reduce execution time on each run of virtual instance.
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: test build
      run: bash ./tests/Actions/TestBuild.sh
